// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGcc5kNm_jNDfmkQpdbKzQxPJNxX9-kqs',
    appId: '1:312621973762:web:f9c0dee3ddb93c3c40021b',
    messagingSenderId: '312621973762',
    projectId: 'auraalert-d2fb4',
    authDomain: 'auraalert-d2fb4.firebaseapp.com',
    storageBucket: 'auraalert-d2fb4.firebasestorage.app',
    measurementId: 'G-DKZ6TBFF6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWRgoe6XncmYjOKuKfjmLoGxQnnJK2v80',
    appId: '1:312621973762:android:7de81b1fd7cf573840021b',
    messagingSenderId: '312621973762',
    projectId: 'auraalert-d2fb4',
    storageBucket: 'auraalert-d2fb4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-yqrjDUImfl9u7dAluRpAZicy2ytLAW4',
    appId: '1:312621973762:ios:318327efa041ddc640021b',
    messagingSenderId: '312621973762',
    projectId: 'auraalert-d2fb4',
    storageBucket: 'auraalert-d2fb4.firebasestorage.app',
    iosBundleId: 'com.example.auraAlert',
  );
}
