// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzjs9GsNawUtw24zz_2XCkJs1Kpa9tyv8',
    appId: '1:227800339925:web:15f14a09dc595e218d595c',
    messagingSenderId: '227800339925',
    projectId: 'auraalert-d00de',
    authDomain: 'auraalert-d00de.firebaseapp.com',
    storageBucket: 'auraalert-d00de.firebasestorage.app',
    measurementId: 'G-FG5ZXPM6FT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgxJOzWM_o7MV6gDQ7Mm8k99m79CsVcHE',
    appId: '1:227800339925:android:03d2c73c5637fe148d595c',
    messagingSenderId: '227800339925',
    projectId: 'auraalert-d00de',
    storageBucket: 'auraalert-d00de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7mkn-cVOCXPILmgrbpANVCXTqSq91faI',
    appId: '1:227800339925:ios:8b641ad2143338ba8d595c',
    messagingSenderId: '227800339925',
    projectId: 'auraalert-d00de',
    storageBucket: 'auraalert-d00de.firebasestorage.app',
    iosBundleId: 'com.example.auraAlert',
  );
}
