/* very important note about the users_reminders collection each document must have a unique number(pk) that is used to delete reminder and such . a unique number is generated by combining a random number plus time of generating : pk = "random(4digits)" + "-" + "timestamp(milliseconds)";  */
import 'dart:math';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:flutter_spinner_time_picker/flutter_spinner_time_picker.dart';
import 'package:iconsax/iconsax.dart';
import 'package:intl/intl.dart';

class CreateReminder extends StatefulWidget {
  const CreateReminder({super.key});

  @override
  State<CreateReminder> createState() => _CreateReminderState();
}

class _CreateReminderState extends State<CreateReminder> {
  late String? userId; // Nullable user ID to prevent issues with UI updates
  late String? userEmail;
  late String? userPhone;

  // Method to store user ID from Firebase Auth and store it in a class-scoped variable
  Future<void> getUserID() async {
    User? user = FirebaseAuth.instance.currentUser;
    if (user != null) {
      setState(() {
        userId = user.uid;
        userEmail = user.email ?? "";
        userPhone = user.phoneNumber ?? "";
      });
    }
  }

  //method to add picked fields to collection user_reminders
  Future<void> addSelectedToDB(
      String userEmail,
      String userPhone,
      String userId,
      String selectedRemindAbout,
      String repeatEveryPick,
      int repeatEveryPick2,
      TimeOfDay selectedTime,
      DateTime selectedDate,
      ) async {
    try {
      // Generate a unique reminder_id using current timestamp and a random number
      int timestamp = DateTime.now().millisecondsSinceEpoch;
      int randomNum = Random().nextInt(9999); // Generate a random number between 0 and 9999
      String reminderId = '$timestamp-$randomNum'; // Combine for unique reminder ID

      // Add the reminder details to the "users_reminders" collection
      await FirebaseFirestore.instance.collection('users_reminders').add({
        'reminder_id': reminderId, // Add the unique reminder_id
        'remind_about': selectedRemindAbout,
        'repeat_frequency': repeatEveryPick,
        'repeat_every': repeatEveryPick2,
        'reminder_time': '${selectedTime.hourOfPeriod == 0 ? 12 : selectedTime.hourOfPeriod}:${selectedTime.minute.toString().padLeft(2, '0')} ${selectedTime.period == DayPeriod.am ? 'AM' : 'PM'}',
        'reminder_date': Timestamp.fromDate(selectedDate), // Save date as Firestore Timestamp
        'timestamp': FieldValue.serverTimestamp(), // Time of adding, helps prevent spamming
        'user_id': userId,
        'user_email': userEmail,
        'user_phone': userPhone,
      });
      if(mounted){
        // Show a confirmation message (Snackbar) after adding the reminder
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Reminder has been added.'),
            backgroundColor: Colors.green,
          ),
        );
      }
    } catch (e) {
      if(mounted){
        // Handle any errors that might occur during the addition process
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Failed to add reminder: ${e.toString()}'),
            backgroundColor: Colors.red,
          ),
        );
      }
    }
  }

  @override
  void initState() {
    super.initState();
    userId = null; // Initialize as null
    getUserID(); // Get user ID
  }

  List<Map<String, dynamic>> data = [
    {
      "left-text": "Remind me about",
      "icon": Iconsax.sun_1,
      "right-text": "Select"
    },
    {
      "left-text": "Repeat Every",
      "icon": Icons.autorenew,
      "right-text": "3 Day"
    },
    {"left-text": "Time", "icon": Iconsax.clock, "right-text": "08:00-AM"},
    {
      "left-text": "Starting Date",
      "icon": Icons.calendar_month_outlined,
      "right-text": "12/10/24"
    },
  ];

  List<Map<String, dynamic>> remindMeAboutData = [
    {"text": "Watering", "icon": Icons.water_drop},
    {"text": "Misting", "icon": "assets/images/water-spray.png"},
    {"text": "Fertilizing", "icon": "assets/images/manure.png"},
    {"text": "Rotating", "icon": Iconsax.sun_1}
  ];

  String selectedRemindAbout = "Select";

  String repeatEveryPick = "Days"; // Moved to class level to retain state
  int repeatEveryPick2 = 3; // Moved to class level to retain state

  //important TimeOfDay is used because the flutter_spinner_time_picker requires it not the DateTime and because its used to save time(HH:SS) not date(DD:MM:YY)
  TimeOfDay selectedTime = TimeOfDay
      .now(); // initial time for right text for time container on pick its updated to the selected time

  DateTime selectedDate = DateTime.now();

  @override
  Widget build(BuildContext context) {
    double screenHeight = MediaQuery.of(context).size.height;
    double screenWidth = MediaQuery.of(context).size.width;
    return Scaffold(
      backgroundColor: Colors.grey.shade100,
      appBar: AppBar(
        automaticallyImplyLeading: false,
        backgroundColor: Colors.grey.shade200,
        toolbarHeight: screenHeight * 0.1,
        bottom: PreferredSize(
          //bottom border of appbar customization
          preferredSize: const Size.fromHeight(2.0),
          child: Container(
            color: Colors.grey.shade400, // bottom border of app bar color
            height: 1.0, //bottom of appbar thickness
          ),
        ),
        title: SafeArea(
          child: Column(
            children: [
              Row(
                children: [
                  GestureDetector(
                    child: const Icon(Iconsax.arrow_circle_left,
                        color: Colors.black87),
                    onTap: () => Navigator.pop(context),
                  ),
                  const SizedBox(width: 10),
                  const Text(
                    "Set Reminder",
                    style: TextStyle(fontWeight: FontWeight.bold),
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
      body: SafeArea(
          child: Column(
            children: [
              for (int i = 0; i < 4; i++)
                Padding(
                  padding: EdgeInsets.only(
                      left: 20.0, right: 20, top: i == 0 ? 30 : 10, bottom: 5),
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(10),
                      color: Colors.white,
                    ),
                    height: 50,
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        Row(
                          children: [
                            const SizedBox(
                              width: 10,
                            ),
                            Container(
                              padding: const EdgeInsets.all(5),
                              decoration: BoxDecoration(
                                  shape: BoxShape
                                      .circle, //make the container a circle around the icon
                                  color: Colors.grey.shade200),
                              child: Icon(data[i]["icon"]),
                            ),
                            const SizedBox(
                              width: 10,
                            ),
                            Text(
                              data[i]["left-text"],
                              style: const TextStyle(
                                  fontWeight: FontWeight.bold, fontSize: 12),
                            )
                          ],
                        ),
                        GestureDetector(
                            child: Row(
                              children: [
                                Text(
                                  i == 0
                                      ? selectedRemindAbout
                                      : i == 1
                                      ? "$repeatEveryPick2 $repeatEveryPick"
                                      : i == 2
                                      ? selectedTime.format(
                                      context) //convert TimeOfDay to string
                                      : i == 3
                                      ? DateFormat('dd/MM/yy')
                                      .format(selectedDate)
                                      .toString() //convert TimeOfDay to string on the format of dd/mm/yy
                                      : data[i]["right-text"],
                                  style: const TextStyle(
                                      fontWeight: FontWeight.w600, fontSize: 12),
                                ),
                                const SizedBox(
                                  width: 7,
                                ),
                                const Icon(
                                  Iconsax.arrow_right_3,
                                  color: Colors.grey,
                                ),
                                const SizedBox(
                                  width: 7,
                                )
                              ],
                            ),
                            onTap: () {
                              if (i == 0) {
                                showModalBottomSheet(
                                  useSafeArea: true,
                                  isScrollControlled: true, // Required to make the keyboard push the sheet up
                                  backgroundColor: Colors.grey.shade200,
                                  context: context,
                                  builder: (BuildContext context) {
                                    return Padding(
                                      // This padding handles the keyboard appearing
                                      padding: EdgeInsets.only(
                                          bottom: MediaQuery.of(context).viewInsets.bottom,
                                          left: 20,
                                          right: 20,
                                          top: 20
                                      ),
                                      child: Wrap( // Wrap adjusts height based on content
                                        children: [
                                          Column(
                                            crossAxisAlignment: CrossAxisAlignment.start,
                                            children: [
                                              const Text(
                                                "Enter details",
                                                style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                                              ),
                                              const SizedBox(height: 15),
                                              // --- YOUR NEW TEXT FIELD ---
                                              Container(
                                                decoration: BoxDecoration(
                                                  color: Colors.white,
                                                  borderRadius: BorderRadius.circular(8),
                                                ),
                                                child: TextField(
                                                  autofocus: true, // Opens keyboard immediately
                                                  decoration: const InputDecoration(
                                                    hintText: "Type here...",
                                                    border: InputBorder.none,
                                                    contentPadding: EdgeInsets.symmetric(horizontal: 15, vertical: 15),
                                                    // Optional: Add an icon to match your style
                                                    prefixIcon: Icon(Icons.edit, color: Colors.grey),
                                                  ),
                                                  onChanged: (value) {
                                                    // Update your variable here
                                                    setState(() {
                                                      selectedRemindAbout = value;
                                                    });
                                                  },
                                                  onSubmitted: (value) {
                                                    // Close the sheet when user presses 'Done' on keyboard
                                                    Navigator.of(context).pop();
                                                  },
                                                ),
                                              ),
                                              const SizedBox(height: 20), // Bottom spacer
                                            ],
                                          ),
                                        ],
                                      ),
                                    );
                                  },
                                );
                              }
                              if (i == 1) {
                                // Show a card with two dropdowns for "Repeat Every" when the user taps the third item (Repeat Every)
                                showModalBottomSheet(
                                  backgroundColor: Colors.white,
                                  context: context,
                                  builder: (BuildContext context) {
                                    return StatefulBuilder(
                                      builder: (BuildContext context,
                                          StateSetter setModalState) {
                                        return Padding(
                                          padding: const EdgeInsets.all(20.0),
                                          child: Card(
                                            color: Colors.grey.shade200,
                                            elevation: 2,
                                            child: Padding(
                                              padding: const EdgeInsets.all(20.0),
                                              child: Column(
                                                mainAxisSize: MainAxisSize.min,
                                                children: [
                                                  const Text(
                                                    "Select Repeat Interval",
                                                    style: TextStyle(
                                                        fontWeight:
                                                        FontWeight.bold),
                                                  ),
                                                  const SizedBox(height: 20),
                                                  Row(
                                                    mainAxisAlignment:
                                                    MainAxisAlignment
                                                        .spaceAround,
                                                    children: [
                                                      // First dropdown for the unit (Days, Weeks, Months)
                                                      Container(
                                                        decoration: BoxDecoration(
                                                          color: Colors
                                                              .white, // Dropdown button background color
                                                          borderRadius:
                                                          BorderRadius.circular(
                                                              8),
                                                        ),
                                                        padding: const EdgeInsets
                                                            .symmetric(
                                                            horizontal: 12),
                                                        child:
                                                        DropdownButton<String>(
                                                          borderRadius:
                                                          BorderRadius.circular(
                                                              8), // Dropdown menu border radius
                                                          dropdownColor: Colors
                                                              .white, // Dropdown menu background color
                                                          value:
                                                          repeatEveryPick, // Default selected value
                                                          iconEnabledColor: Colors
                                                              .grey, // Dropdown arrow color
                                                          style: const TextStyle(
                                                              color: Colors
                                                                  .black), // Dropdown text color
                                                          underline:
                                                          Container(), // Remove default underline
                                                          items: [
                                                            'Days',
                                                            'Weeks',
                                                            'Months'
                                                          ].map((String value) {
                                                            return DropdownMenuItem<
                                                                String>(
                                                              value: value,
                                                              child: Text(value),
                                                            );
                                                          }).toList(),
                                                          onChanged:
                                                              (String? newValue) {
                                                            setModalState(() {
                                                              repeatEveryPick =
                                                              newValue!; //update the value of repeatEveryPick2 in the top ui (the ui of the popup)
                                                            });
                                                            setState(() {
                                                              repeatEveryPick =
                                                              newValue!; // update the value of repeatEveryPick in the bottom ui (the parent ui that have the set reminder page)
                                                            }); // Update parent widget state
                                                          },
                                                        ),
                                                      ),

                                                      // Second dropdown for the number (1, 2, 3, ..., 30)
                                                      Container(
                                                        decoration: BoxDecoration(
                                                          color: Colors
                                                              .white, // Dropdown button background color
                                                          borderRadius:
                                                          BorderRadius.circular(
                                                              8),
                                                        ),
                                                        padding: const EdgeInsets
                                                            .symmetric(
                                                            horizontal: 12),
                                                        child: DropdownButton<int>(
                                                          borderRadius:
                                                          BorderRadius.circular(
                                                              8), // Dropdown menu border radius
                                                          dropdownColor: Colors
                                                              .white, // Dropdown menu background color
                                                          value:
                                                          repeatEveryPick2, // Default selected value
                                                          iconEnabledColor: Colors
                                                              .grey, // Dropdown arrow color
                                                          style: const TextStyle(
                                                              color: Colors
                                                                  .black), // Dropdown text color
                                                          underline:
                                                          Container(), // Remove default underline
                                                          items: List.generate(
                                                              30,
                                                                  (index) =>
                                                              index + 1)
                                                              .map((int value) {
                                                            return DropdownMenuItem<
                                                                int>(
                                                              value: value,
                                                              child: Text(
                                                                  value.toString()),
                                                            );
                                                          }).toList(),
                                                          onChanged:
                                                              (int? newValue) {
                                                            setModalState(() {
                                                              repeatEveryPick2 =
                                                              newValue!; // update the value of repeatEveryPick2 in the top ui (the ui of the popup)
                                                            });
                                                            setState(() {
                                                              repeatEveryPick2 =
                                                              newValue!; // update the value of repeatEveryPick2 in the bottom ui (the parent ui that have the set reminder page)
                                                            }); // Update parent widget state
                                                          },
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ],
                                              ),
                                            ),
                                          ),
                                        );
                                      },
                                    );
                                  },
                                );
                              } else if (i == 2) {
                                // Show the spinner time picker directly in the modal
                                showModalBottomSheet(
                                    backgroundColor: Colors.white,
                                    context: context,
                                    builder: (BuildContext context) {
                                      return SizedBox(
                                        height: screenHeight * 0.3,
                                        child: Column(
                                          children: [
                                            Expanded(
                                              child: Theme(
                                                // i raise my hat for you hashem for finding out that theme changes the am/pm color after several hours of reading the package source code , because the dumb person who wrote the package didn't point out that to change am / pm you gotta change the theme of the widget
                                                data: ThemeData(
                                                  colorScheme:
                                                  ColorScheme.fromSwatch()
                                                      .copyWith(
                                                    primary: Colors
                                                        .green, //focused am/pm text color
                                                    onPrimary: Colors
                                                        .white, // unfocused container color of am /pm
                                                    secondary: Colors
                                                        .greenAccent, // focused am /pm container color
                                                  ),
                                                ),
                                                child: SpinnerTimePicker(
                                                  initTime:
                                                  selectedTime, // The selected time
                                                  is24HourFormat:
                                                  false, // AM/PM format
                                                  spinnerHeight: screenHeight *
                                                      0.2, // Height of the spinner
                                                  spinnerWidth:
                                                  100, // Width of the spinner
                                                  elementsSpace:
                                                  20, // Space between spinner elements
                                                  digitHeight:
                                                  50, // Height of the digits
                                                  spinnerBgColor: Colors
                                                      .white, // Background color of the spinner
                                                  selectedTextStyle:
                                                  const TextStyle(
                                                    fontSize: 24,
                                                    color: Colors
                                                        .black, // You can use green here if needed
                                                    fontWeight: FontWeight.bold,
                                                  ), // Style for selected text
                                                  nonSelectedTextStyle:
                                                  const TextStyle(
                                                    fontSize: 18,
                                                    color: Colors.grey,
                                                  ), // Style for non-selected text
                                                  onChangedSelectedTime:
                                                      (TimeOfDay selected) {
                                                    setState(() {
                                                      selectedTime = selected;
                                                    });
                                                  },
                                                ),
                                              ),
                                            ),
                                            const SizedBox(
                                              height: 10,
                                            ),
                                            Row(
                                              mainAxisAlignment:
                                              MainAxisAlignment.center,
                                              children: [
                                                TextButton(
                                                  child: const Text('Cancel',
                                                      style: TextStyle(
                                                          color: Colors.black,
                                                          fontWeight: FontWeight
                                                              .bold)), // Cancel button color
                                                  onPressed: () {
                                                    setState(() {
                                                      selectedTime =
                                                          TimeOfDay.now();
                                                    });
                                                    Navigator.pop(context);
                                                  },
                                                ),
                                                TextButton(
                                                  child: const Text('OK',
                                                      style: TextStyle(
                                                          color: Colors.green,
                                                          fontWeight: FontWeight
                                                              .bold)), // OK button color
                                                  onPressed: () {
                                                    Navigator.of(context).pop();
                                                  },
                                                ),
                                              ],
                                            ),
                                            const SizedBox(
                                              height: 20,
                                            ),
                                          ],
                                        ),
                                      );
                                    });
                              } else if (i == 3) {
                                // Show custom date picker dialog
                                showDialog<DateTime>(
                                  context: context,
                                  builder: (BuildContext context) {
                                    DateTime selectedDate = this
                                        .selectedDate; // Initialize with current selected date
                                    return Dialog(
                                      backgroundColor: Colors.white,
                                      child: Theme(
                                        data: ThemeData.light().copyWith(
                                          primaryColor: Colors
                                              .green, // Header background color
                                          hintColor: Colors
                                              .green, // Accent color for selection
                                          colorScheme: const ColorScheme.light(
                                              primary:
                                              Colors.green), // Selection color
                                          buttonTheme: const ButtonThemeData(
                                              textTheme: ButtonTextTheme
                                                  .primary), // Button theme
                                        ),
                                        child: Column(
                                          mainAxisSize: MainAxisSize.min,
                                          children: <Widget>[
                                            Container(
                                              padding: const EdgeInsets.all(20),
                                              child: const Text(
                                                'Select Date',
                                                style: TextStyle(
                                                    fontSize: 17,
                                                    color: Colors
                                                        .green), // Title color
                                              ),
                                            ),
                                            // Date Picker
                                            SizedBox(
                                              height: screenHeight * .45,
                                              child: CalendarDatePicker(
                                                initialDate: selectedDate,
                                                firstDate: DateTime.now(),
                                                lastDate: DateTime(2101),
                                                onDateChanged: (DateTime date) {
                                                  selectedDate =
                                                      date; // Update selected date
                                                },
                                              ),
                                            ),
                                            Row(
                                              mainAxisAlignment:
                                              MainAxisAlignment.end,
                                              children: [
                                                TextButton(
                                                  child: const Text('Cancel',
                                                      style: TextStyle(
                                                          color: Colors.black,
                                                          fontWeight: FontWeight
                                                              .bold)), // Cancel button color
                                                  onPressed: () {
                                                    setState(() {
                                                      selectedDate = DateTime.now();
                                                    });
                                                    Navigator.of(context)
                                                        .pop(selectedDate);
                                                  },
                                                ),
                                                TextButton(
                                                  child: const Text('OK',
                                                      style: TextStyle(
                                                          color: Colors.green,
                                                          fontWeight: FontWeight
                                                              .bold)), // OK button color
                                                  onPressed: () {
                                                    Navigator.of(context)
                                                        .pop(selectedDate);
                                                  },
                                                ),
                                              ],
                                            ),
                                          ],
                                        ),
                                      ),
                                    );
                                  },
                                ).then((pickedDate) {
                                  if (pickedDate != null) {
                                    setState(() {
                                      selectedDate =
                                          pickedDate; // Update the class var selectedDate to the value that user picked
                                    });
                                  }
                                });
                              }
                            })
                      ],
                    ),
                  ),
                ),
              const Spacer(), //this widget takes up the remaining space in the column, pushing the "Set Reminder" button to the bottom of page(column).
              GestureDetector(
                child: Padding(
                  padding:
                  const EdgeInsets.symmetric(horizontal: 20.0, vertical: 10),
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(8),
                      color: Colors.green.shade400,
                    ),
                    height: 60,
                    child: const Center(
                      child: Text(
                        "Set Reminder",
                        style: TextStyle(
                            color: Colors.white, fontWeight: FontWeight.bold),
                      ),
                    ),
                  ),
                ),
                onTap: () async{
                  if (selectedRemindAbout == "Select") {
                    ScaffoldMessenger.of(context).showSnackBar(
                      const SnackBar(
                        backgroundColor: Colors.red,
                        content: Text('Kindly ensure all options are filled out.'),
                      ),
                    );
                  } else {
                    //make sure you await adding reminder to db
                    await addSelectedToDB(
                        userEmail!,
                        userPhone!,
                        userId!,
                        selectedRemindAbout,
                        repeatEveryPick,
                        repeatEveryPick2,
                        selectedTime,
                        selectedDate);

                    //don't navigate before you await adding reminder to db
                    // Navigator.pushReplacement(
                    //   context,
                    //   CupertinoPageRoute(
                    //     builder: (context) => const MyNavBar(globalSelectedIndex: 1),
                    //   ),
                    // );
                  }
                },
              ),
              const SizedBox(
                height: 20,
              )
            ],
          )),
    );
  }
}